// qhlist220000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
(["quest_city":"白驼附近", "quest": "村姑",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "寡妇",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "金花",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "老材",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "农民",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "樵夫",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "铁匠",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "陪练童子",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "白衣少女",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "农家妇女",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "丫环",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 
(["quest_city":"白驼附近", "quest": "张妈",  "quest_type": "杀",  "time":  200,  "exp_bonus":  68,  "pot_bonus":  32,  "score" : 20 ]), 

(["quest_city":"扬州附近", "quest":  "史青山",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"扬州附近", "quest":  "崔莺莺",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"扬州附近", "quest":  "茅十八",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"扬州附近", "quest":  "范一飞",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"扬州附近", "quest":  "风良",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"扬州附近", "quest":  "高三娘子",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"扬州附近", "quest":  "吕正平",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"扬州附近", "quest":  "马超兴",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"北京附近", "quest":  "卖花姑娘",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "庄夫人",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "高彦超",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "关安基",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "女管家",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "胡掌柜",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "客店伙计",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "屠宰场伙计",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "药铺伙计",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "李力世",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "双儿",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "铁匠",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "吴六奇",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "戏子",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"北京附近", "quest":  "徐天川",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"长安附近", "quest":  "酸秀才",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"长安附近", "quest":  "茶博士",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"大理附近", "quest":  "士兵",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "台夷商贩",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "南国姑娘",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "宫女",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "管家",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "养花女",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "霍先生",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "江湖艺人",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "砍竹人",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "盛皮罗客商",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "猎人",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "台夷猎人",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "牧羊女",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "牧羊人",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "农夫",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "台夷农妇",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "农夫",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "摆夷老叟",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "皮货商",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "破嗔",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "破疑",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "少女",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "石匠",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "台夷商贩",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "素衣卫士",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "黄衣卫士",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "锦衣卫士",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "乌夷商贩",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "小道姑",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "薛老板",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "养蚕女",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "游客",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "渔夫",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近", "quest":  "巴天石",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近",  "quest":  "刀白凤",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近",  "quest":  "范骅",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近",  "quest":  "傅思归",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近",  "quest":  "高升泰",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近",  "quest":  "古笃诚",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近",  "quest":  "华赫艮",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近",  "quest":  "朱丹臣",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"大理附近",  "quest":  "褚万里",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"佛山附近", "quest":  "张朝唐",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"佛山附近", "quest":  "张康",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"佛山附近", "quest":  "钟四嫂",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"佛山附近", "quest":  "钟小二",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"福州附近", "quest":  "白二",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"福州附近", "quest":  "陈七",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"福州附近", "quest":  "崔镖头",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"福州附近", "quest":  "史镖头",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"福州附近", "quest":  "王夫人",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"福州附近", "quest":  "郑镖头",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"归云庄附近", "quest":  "韩宝驹",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "韩小莹",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "柯镇恶",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "南希仁",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "裘千丈",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "全金发",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "书童",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "小菊",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "小兰",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "陆冠英",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "张阿生",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"归云庄附近", "quest":  "朱聪",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"古墓附近", "quest":  "孙婆婆",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"杭州附近", "quest":  "红花会众",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"杭州附近", "quest":  "绿营会众",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"杭州附近", "quest":  "李沅芷",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"杭州附近", "quest":  "庄允城",  "quest_type": "杀",  "time": 300,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"恒山附近", "quest":  "仪和",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"恒山附近", "quest":  "秦绢",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"恒山附近", "quest":  "仪清",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"恒山附近", "quest":  "仪文",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"恒山附近", "quest":  "哑妇",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"恒山附近", "quest":  "郑萼",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"恒山附近", "quest":  "仪质",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"衡阳附近", "quest":  "茶博士",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"衡阳附近", "quest":  "刘夫人",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"衡阳附近", "quest":  "刘菁",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"衡阳附近", "quest":  "刘芹",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"衡阳附近", "quest":  "米为义",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"衡阳附近", "quest":  "向大年",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"衡阳附近", "quest":  "曲非烟",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"衡阳附近", "quest":  "仪琳",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"黄河附近", "quest":  "老秀才",  "quest_type": "杀",  "time": 200,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"黄河附近", "quest":  "祖千秋",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"黄河附近", "quest":  "西夏兵",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"黄河附近", "quest":  "采石人",  "quest_type": "杀",  "time": 450,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"华山附近", "quest":  "陆大有",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"华山附近", "quest":  "高根明",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"华山附近", "quest":  "梁发",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"华山附近", "quest":  "小猴",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"华山附近", "quest":  "陆大有",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"华山附近", "quest":  "施戴子",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"华山附近", "quest":  "岳灵珊",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"华山附近", "quest":  "翠花",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"梅庄附近", "quest":  "丁坚",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"梅庄附近", "quest":  "施令威",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"全真教附近", "quest":  "陈志益",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"全真教附近", "quest":  "姬清虚",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"全真教附近", "quest":  "皮清玄",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"全真教附近", "quest":  "尹志平",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"全真教附近", "quest":  "侯员外",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"全真教附近", "quest":  "赵志敬",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"泉州附近", "quest":  "刘国轩",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"苏州附近", "quest": "小孩",  "quest_type": "杀",  "time":  350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]), 
(["quest_city":"苏州附近", "quest": "苏州女孩",  "quest_type": "杀",  "time":  350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]), 
(["quest_city":"苏州附近", "quest": "苏州少女",  "quest_type": "杀",  "time":  350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]), 
(["quest_city":"苏州附近", "quest": "游方和尚",  "quest_type": "杀",  "time":  350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]), 

(["quest_city":"泰山附近", "quest":  "迟百城",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"泰山附近", "quest":  "建除道人",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"泰山附近", "quest":  "江百胜",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"泰山附近", "quest":  "游方和尚",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"泰山附近", "quest":  "天柏道人",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"泰山附近", "quest":  "天松道人",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"泰山附近", "quest":  "天乙道人",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"天龙寺附近", "quest":  "护塔僧",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"天龙寺附近", "quest":  "老年僧人",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"天龙寺附近", "quest":  "扫地僧",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"逍遥林附近", "quest":  "冯阿三",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"逍遥林附近", "quest":  "苟读",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"逍遥林附近", "quest":  "康广陵",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"逍遥林附近", "quest":  "薛慕华",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"伊犁附近", "quest":  "阿拉木罕",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"伊犁附近", "quest":  "阿凡提",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"伊犁附近", "quest":  "买卖提",  "quest_type": "杀",  "time": 200,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"伊犁附近", "quest":  "波斯商人",  "quest_type": "杀",  "time": 200,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"雪山寺附近", "quest":  "刘承风",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"雪山寺附近", "quest":  "陆天抒",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"雪山寺附近", "quest":  "水岱",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"雪山寺附近", "quest":  "央宗",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"雪山寺附近", "quest":  "卓玛",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"燕子坞附近", "quest":  "阿朱",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"峨嵋山附近",  "quest":  "贝锦仪",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静道师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "道明小师父",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "方碧琳",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静风师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静和师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静慧师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "纪晓芙",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静迦师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静空师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "李明霞",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "赵灵珠",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "苏梦清",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "文方小师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "文晖小师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "文清小师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "文音小师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静闲师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静虚师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静玄师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静照师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "静真师太",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"峨嵋山附近", "quest":  "宋青书",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"丐帮附近", "quest":  "江上游",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "快活三",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "何不净",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "李斧头",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "黎生",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "马俱为",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "莫不收",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "裘万家",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "余洪兴",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "赵狗儿",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"丐帮附近", "quest":  "左全",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"少林寺附近", "quest":  "澄观",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "澄行",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "澄意",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "澄志",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "道相禅师",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "道象禅师",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "道一禅师",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "道正禅师",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "慧合尊者",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "慧洁尊者",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "慧真尊者",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "清法比丘",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "清观比丘",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "清乐比丘",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "清善比丘",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "清为比丘",  "quest_type": "杀",  "time": 350,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"少林寺附近", "quest":  "行者",  "quest_type": "杀",  "time": 200,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"桃花岛附近", "quest":  "冯默风" ,  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"桃花岛附近", "quest":  "曲灵风" ,  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"桃花岛附近",  "quest":  "黄蓉",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"桃花岛附近", "quest":  "程英",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"武当山附近",  "quest":  "道童",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"武当山附近", "quest":  "明月",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"武当山附近", "quest":  "清风",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"武当山附近", "quest":  "清虚道长",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"武当山附近", "quest":  "守园道长",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"云龙门附近", "quest":  "玄贞道长",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"碎叶附近", "quest":  "周老板",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"碎叶附近", "quest":  "沈大夫",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),
(["quest_city":"碎叶附近", "quest":  "秦掌柜",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"凉州附近", "quest":  "妙庆",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20 ]),

(["quest_city":"盛京附近","quest": "马大嫂",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"盛京附近","quest": "范文程",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"盛京附近","quest": "李大姐",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),

(["quest_city":"大同附近","quest": "张天有",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "巧手妹妹",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "胡迈",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "任一力",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "刘铁",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "黄富贵",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "诸葛武",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "手编老人",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "钟济世",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "李大爷",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "梁员外",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"大同附近","quest": "和全利",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),

(["quest_city":"天水附近","quest": "雷开远",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"天水附近","quest": "老僧",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"天水附近","quest": "周铁匠",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"天水附近","quest": "王济世",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),

(["quest_city":"关中附近","quest": "林玉姣",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"关中附近","quest": "林一鸣",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"关中附近","quest": "林天雄",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"关中附近","quest": "林天豪",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"关中附近","quest": "林天保",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"关中附近","quest": "莫飞云",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
(["quest_city":"关中附近","quest": "周员外",  "quest_type": "杀",  "time": 400,  "exp_bonus":  90,  "pot_bonus":  42,  "score" : 20  ]),
});

mapping query_quest()
{
 return quest[random(sizeof(quest))];
}
