//qwlist200000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest=({
(["quest":"白色长袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"海口大碗","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"草莓","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"柴刀","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"大刀","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"金蛇胆","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"青蛇胆","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"青色丝袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"蛇胆膏","quest_type":"寻","time": 500,"exp_bonus":8,"pot_bonus":3,"score" :20,"quest_city":"白驼"]),
(["quest":"蛇皮","quest_type":"寻","time": 500,"exp_bonus":8,"pot_bonus":3,"score" :20,"quest_city":"白驼"]),
(["quest":"蛇肉","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"绣花鞋","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"兔肉","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"白色长袍","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"海口大碗","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"蛋糕","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"木柴","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"豆浆","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"蛇胆粉","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"引路神蛇","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"蛇杖","quest_type":"寻","time": 400,"pot_bonus":56,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"绣花鞋","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"大刀","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),
(["quest":"钥匙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"白驼"]),

(["quest":"牛皮酒袋","quest_type":"寻","time": 200,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"草鞋","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"绣花小鞋","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"金戒指","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"狗皮","quest_type":"寻","time": 400,"pot_bonus":56,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"金项链","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"牢房钥匙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":20,"score" :20,"quest_city":"扬州"]),
(["quest":"包子","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"黑龙鞭","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":20,"score" :20,"quest_city":"扬州"]),
(["quest":"药粉","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"铁甲","quest_type":"寻","time": 400,"exp_bonus":120,"pot_bonus":9,"score" :20,"quest_city":"扬州"]),
(["quest":"长剑","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"金创药","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"花雕酒袋","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"金项链","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"粉红绸衫","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"碧螺春","quest_type":"寻","time":400,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"扬州"]),
(["quest":"火折","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":YEL"三字经"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"扬州"]),
(["quest":YEL"百家姓"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"扬州"]),
(["quest":YEL"千字文"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"扬州"]),
(["quest":YEL"论语"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"扬州"]),
(["quest":"拳谱总诀","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"扬州"]),
(["quest":"麻布袋","quest_type":"寻","time": 200,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"皮背心","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"头盔","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"武者项圈","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"肚带","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"牛皮盾","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"护腕","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"指套","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"护腰","quest_type":"寻","time": 200,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"草鞋","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"皮靴","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"皮手套","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"钢刀","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"铁棍","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"普通匕首","quest_type":"寻","time": 200,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"屠刀","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"铁锤","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"长剑","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"治病理气丸","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"烤鸡腿","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"翡翠豆腐","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"五香花生","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"祁门红茶","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"铁观音","quest_type":"寻","time": 200,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"武夷岩茶","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"信阳毛尖","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"都匀细毛尖","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"君山银针","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"六安瓜片","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"黄山毛峰","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"西湖龙井","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"军服","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":"衙役服","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"扬州"]),
(["quest":HIW"大石头"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"扬州"]),
(["quest":GRN"大树枝"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"扬州"]),

(["quest":"红烧狗肉","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"丐帮"]),
(["quest":"竹棒","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"丐帮"]),

(["quest":"拂尘","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"峨嵋"]),
(["quest":"皮腰带","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"峨嵋"]),
(["quest":"淡黄衫","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"峨嵋"]),
	
(["quest":"绸袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"长安"]),
(["quest":"粗布衣","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"长安"]),

(["quest":"青色道袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"嘉兴"]),

(["quest":"虎皮","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"铁掌"]),

(["quest":"摆夷短裙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"对衿褂子","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"黄衣军服","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"砍刀","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"窄裉袄","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"贝壳项链","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"蛮刀","quest_type":"寻","time": 700,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"毛毯","quest_type":"寻","time": 700,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"白纱挑线镶边裙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"台夷短裙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"筒裙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"台夷头巾","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"乌夷长裙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"乌夷大麾","quest_type":"寻","time": 400,"pot_bonus":56,"pot_bonus":26,"score" :20,"quest_city":"大理"]),
(["quest":"白衣","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"白绸衫","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"圆领小袄","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":"纺纱机","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"大理"]),
(["quest":HIR"山茶花"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIG"叶儿粑"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIR"宣威火腿"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIY"落第秀才"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIB"眼"HIW"儿媚"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIR"红妆"HIW"素裹"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIW"抓破"HIG"美"NOR"人"HIR"脸"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIW"倚"HIG"栏"HIR"娇"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIR"十八学士"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIG"十三太保"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIB"八仙过海"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIR"七仙女"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":MAG"风"WHT"尘三"HIR"侠"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIR"二"WHT"乔"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIG"八宝妆"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIW"满月"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":WHT"何首乌"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),
(["quest":HIW"龟苓膏"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"大理"]),

(["quest":"熊胆干","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"关外"]),

(["quest":"粽子","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"归云庄"]),

(["quest":"长袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"燕京"]),

(["quest":"白布长袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"明教"]),
(["quest":"铁背心","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"明教"]),
(["quest":"长鞭","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"明教"]),
	
(["quest":"荷兰火枪","quest_type":"寻","time": 300,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"台湾"]),
	
(["quest":"禅杖","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"金边黑布袈裟","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"青布僧衣","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"灰布镶边袈裟","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"青布镶边袈裟","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"齐眉棍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"白布黑边袈裟","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"青布僧衣","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"铁手掌","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"黄布袈裟","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"护法袈裟","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"少林"]),
(["quest":"旧竹片","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"少林"]),
(["quest":"铁手掌","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"少林"]),
(["quest":YEL"易筋经"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"少林"]),
	
(["quest":"百花腹蛇膏","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"神龙岛"]),
(["quest":"无名花","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"神龙岛"]),
(["quest":"金蛇胆","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"神龙岛"]),
(["quest":"水蜜桃","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"神龙岛"]),
(["quest":"腹蛇胆","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"神龙岛"]),
(["quest":"雄黄","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"神龙岛"]),
(["quest":"神龙八式手法","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"神龙岛"]),

(["quest":"青布袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"桃花岛"]),
(["quest":"醉仙茶","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"桃花岛"]),
(["quest":"粗布袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"桃花岛"]),
(["quest":"桃花糕","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"桃花岛"]),
(["quest":"束发金带" ,"quest_type":"寻","time": 700,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"桃花岛"]),
(["quest":"明珠","quest_type":"寻","time": 800,"exp_bonus":8,"pot_bonus":20,"score" :20,"quest_city":"桃花岛"]),
(["quest":"桃木剑","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"桃花岛"]),
(["quest":"布阵箱","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"桃花岛"]),
(["quest":"玉萧","quest_type":"寻","time": 600,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"桃花岛"]),
(["quest":"旋风扫叶腿法","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"桃花岛"]),
(["quest":HIY"「易经序卦篇」"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"桃花岛"]),
(["quest":HIY"「易经说卦篇」"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"桃花岛"]),
(["quest":HIY"「易经杂卦篇」"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"桃花岛"]),
(["quest":HIY"「易经系辞篇」"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"桃花岛"]),
	
(["quest":"锦盒","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"天龙寺"]),
(["quest":"香","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"天龙寺"]),

(["quest":"黄衫","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"侠客岛"]),

(["quest":"石块","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"福州"]),

(["quest":"小蒲团","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"逍遥"]),
(["quest":"米饭","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"逍遥"]),
(["quest":"易筋经文学篇","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"逍遥"]),

(["quest":"蒙汗药","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"沙虫壳","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"羊鞭","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"长鞭","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"波斯长袍","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"冬不拉","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"小毛驴","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"哈密瓜","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"伊犁马","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"马奶酒壶","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"馕","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"铜钹","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"铜鼓","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"铜号","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"星宿海"]),
(["quest":"『星宿毒经〖上册〗』","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"星宿海"]),
(["quest":"『星宿毒经〖下册〗』","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"星宿海"]),
(["quest":HIM"烟雾弹"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"星宿海"]),
(["quest":HIG"炼心弹"NOR,"quest_type":"寻","time":300,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"星宿海"]),
(["quest":HIG"青葫芦"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"星宿海"]),
(["quest":HIG"碧磷针"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"星宿海"]),
	
(["quest":"阿拉伯弯刀","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"天山"]),
(["quest":"维吾尔族长袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"天山"]),

(["quest":"鸟羽大氅","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"雪山"]),
(["quest":"法轮","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"雪山"]),
(["quest":"木棍","quest_type":"寻","time": 500,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"雪山"]),
(["quest":"牛皮袋","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"雪山"]),
(["quest":"青稞面","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"雪山"]),
	
(["quest":"青布长衫","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"杭州"]),
(["quest":RED"东坡肉"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"杭州"]),
(["quest":HIG"凝碧剑"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"杭州"]),
(["quest":GRN"酒瓶"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":" 杭州"]),
(["quest":HIY"百果油包"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":" 杭州"]),
(["quest":YEL"叫化童鸡"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":" 杭州"]),
(["quest":RED"西湖醋鱼"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":" 杭州"]),
(["quest":HIR"桂花鲜栗羹"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":" 杭州"]),
(["quest":GRN"酒瓶"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":" 杭州"]),
(["quest":RED"龙井虾仁"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":" 杭州"]),

(["quest":"熟铁扁担","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"归云庄"]),
(["quest":"杆秤","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"归云庄"]),
(["quest":"尖刀","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"归云庄"]),
(["quest":"九节鞭","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"归云庄"]),
(["quest":"短刀","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"归云庄"]),
(["quest":"油纸折扇","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"归云庄"]),
(["quest":HIG"青布衣"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"归云庄"]),

 (["quest":"地牢钥匙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"日月"]),
(["quest":"枣红缎面皮袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"日月"]),
(["quest":"大珍珠","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"日月"]),
(["quest":"紫绸衫","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"日月"]),
(["quest":"紫金锤","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"日月"]),
	
(["quest":"丧门斧","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"黄河九曲"]),
(["quest":"葛布长袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"黄河九曲"]),
(["quest":"分水刺","quest_type":"寻","time": 600,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"黄河九曲"]),
(["quest":"三股叉","quest_type":"寻","time": 600,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"黄河九曲"]),
(["quest":"大斧头","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"黄河九曲"]),
(["quest":"夜行水靠","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"黄河九曲"]),
(["quest":"铁锹","quest_type":"寻","time": 400,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"黄河九曲"]),
(["quest":HIC"鹅卵石"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"黄河九曲"]),

(["quest":"斗篷","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"灵鹫宫"]),
(["quest":"冰雪翡翠糕","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"灵鹫宫"]),
(["quest":"青衣","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"灵鹫宫"]),
(["quest":"酸梅汤","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"灵鹫宫"]),
(["quest":"天山折梅手法图上卷","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"灵鹫宫"]),
(["quest":"天山折梅手法图下卷","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"灵鹫宫"]),
(["quest":"天山六阳掌法图上册","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"灵鹫宫"]),
(["quest":"天山六阳掌法图下册","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"灵鹫宫"]),
(["quest":"天羽奇剑剑谱","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"灵鹫宫"]),

(["quest":"道德经「上卷」","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"道德经「下卷」","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"道德经","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"太极十三势","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"道德经「第一章」","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"道德经「第十三章」","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"道德经「第十六章」","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"道德经「第十八章」","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"道德经「第二章」","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
(["quest":"道德经「第八章」","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"武当"]),
	
(["quest":RED"樱桃火腿"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"慕容山庄"]),
(["quest":HIG"荷叶冬笋汤"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"慕容山庄"]),
(["quest":WHT"菱白虾仁"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"慕容山庄"]),

(["quest":RED"佛跳墙"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"福州"]),
	
(["quest":HIR"红绫袄"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"皇宫"]),

(["quest":HIC"君子剑"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"绝情谷"]),
		
(["quest":HIY"独脚铜人"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"关外"]),
(["quest":HIC"铁琵琶"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"关外"]),
	
(["quest":"菜刀","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"佛山"]),
(["quest":HIW"白合花"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"佛山"]),
(["quest":HIR"莎椤花"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"佛山"]),
(["quest":HIB"蕙兰花"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"佛山"]),
(["quest":HIW"石块"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"佛山"]),
(["quest":GRN"小树枝"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"佛山"]),
		
(["quest":WHT"灰色道袍"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
(["quest":HIG"青色道袍"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
(["quest":WHT"灰色道袍"NOR,"quest_type":"寻","time":200,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
(["quest":HIB"乌龟甲"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
(["quest":YEL"茯苓"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
(["quest":HIW"没药"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
(["quest":HIY"田七"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
(["quest":HIR"熊胆"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
(["quest":RED"血竭"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"全真"]),
	
(["quest":HIY"黄色袈裟"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"雪山"]),
(["quest":HIW"银轮"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"雪山"]),
(["quest":"密宗心经","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"雪山"]),

(["quest":"风雷堂令牌","quest_type":"寻","time":500,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"黑木崖"]),
(["quest":"白虎堂令牌","quest_type":"寻","time":500,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"黑木崖"]),
(["quest":"青龙堂令牌","quest_type":"寻","time":500,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"黑木崖"]),
(["quest":"天香堂令牌","quest_type":"寻","time":500,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"黑木崖"]),

(["quest":"辟邪剑谱","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"华山"]),
(["quest":"华山剑谱","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"华山"]),
(["quest":HIG"碧水剑"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"华山"]),
(["quest":CYN"龙泉剑"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"华山"]),
(["quest":HIR"正气吟"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"华山"]),
(["quest":MAG"紫霞密芨"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"华山"]),

(["quest":"群星璀璨图","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"梅庄"]),
(["quest":"无忧红花","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"梅庄"]),
(["quest":"南海神木","quest_type":"寻","time":600,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"梅庄"]),
(["quest":HIG"绿玉洞箫"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"梅庄"]),
(["quest":HIR"红玉钥匙"NOR,"quest_type":"寻","time":400,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"梅庄"]),
(["quest":BLK"黑木令"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"梅庄"]),
(["quest":"黑色长衫","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"梅庄"]),
(["quest":"镔铁判官笔","quest_type":"寻","time": 600,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"梅庄"]),
(["quest":"绣梅青衣","quest_type":"寻","time": 600,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"梅庄"]),
(["quest":"红绸","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"梅庄"]),
(["quest":"无忧红花","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"梅庄"]),
(["quest":"南海神木","quest_type":"寻","time": 600,"exp_bonus":86,"pot_bonus":40,"score" :20,"quest_city":"梅庄"]),
(["quest":"血棋衣","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"梅庄"]),
		
(["quest":"玉女剑谱","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"古墓"]),
(["quest":HIM"玉女心经上册"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"古墓"]),
(["quest":HIM"玉女心经下册"NOR,"quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"古墓"]),
(["quest":HIC"淑女剑"NOR,"quest_type":"寻","time":500,"exp_bonus":110,"pot_bonus":54,"score":5,"quest_city":"古墓"]),
(["quest":"白袍","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"古墓"]),

(["quest":"锦缎","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":26,"score" :20,"quest_city":"北京"]),
(["quest":"腰带","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"北京"]),
(["quest":"云龙鞭法","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"北京"]),
(["quest":"云龙剑谱","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"北京"]),
(["quest":"云龙剑谱","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"北京"]),
(["quest":"云龙经","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"北京"]),
(["quest":"云龙经「上卷」","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"北京"]),
(["quest":"云龙经「下卷」","quest_type":"寻","time":800,"exp_bonus":240,"pot_bonus":50,"score":5,"quest_city":"北京"]),
(["quest":"金叶","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"北京"]),
(["quest":"屠刀","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"北京"]),

(["quest":"磨刀石","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"天水"]),
(["quest":"铜钥匙","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"天水"]),
(["quest":"红兜兜","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"天水"]),
	
(["quest":"红色的细针","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"兴国禅寺"]),
(["quest":"绿色的细针","quest_type":"寻","time": 400,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"兴国禅寺"]),

(["quest":"冰糖葫芦","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"侯集镇"]),
(["quest":"二胡","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"侯集镇"]),
(["quest":"水囊","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"侯集镇"]),
	
(["quest":"旧书","quest_type":"寻","time": 300,"exp_bonus":80,"pot_bonus":40,"score" :20,"quest_city":"宁远"]),
	
(["quest":"蓑衣","quest_type":"寻","time": 500,"exp_bonus":100,"pot_bonus":50,"score" :20,"quest_city":"华亭"]),

(["quest":"养身丹","quest_type":"寻","time": 500,"exp_bonus":100,"pot_bonus":50,"score" :20,"quest_city":"雪亭镇"]),
(["quest":"阳春面","quest_type":"寻","time": 500,"exp_bonus":100,"pot_bonus":50,"score" :20,"quest_city":"雪亭镇"]),
	
(["quest":"纸钱","quest_type":"寻","time": 500,"exp_bonus":100,"pot_bonus":50,"score" :20,"quest_city":"绮云镇"]),
(["quest":"纸花","quest_type":"寻","time": 500,"exp_bonus":100,"pot_bonus":50,"score" :20,"quest_city":"绮云镇"]),
});

mapping query_quest()
{
return quest[random(sizeof(quest))];
}


