#include <ansi.h>
mapping *wheres=({
          
      (["chinese":                "大理北门",
       "weizhi" :              "/d/dali/northgate",]),  
      (["chinese":                "扬州密林",
       "weizhi" :              "/d/city/jiaowai5",]),  
     (["chinese":                "峨嵋草棚",
       "weizhi" :              "/d/emei/caopeng",]),
     (["chinese":                "扬州西门",
       "weizhi" :              "/d/city/ximen",]),
     (["chinese":                "雪山土路",
       "weizhi" :              "/d/xueshan/tulu2",]),
     (["chinese":                "苏州留园",
       "weizhi" :              "/d/suzhou/liuyuan",]),
     (["chinese":                "苏州寒山寺",
       "weizhi" :              "/d/suzhou/hanshansi",]),
     (["chinese":                "杭州飞来峰",
       "weizhi" :              "/d/hangzhou/feilaifeng",]),
     (["chinese":                "杭州净慈寺",
       "weizhi" :              "/d/hangzhou/jingcisi",]),
     (["chinese":                "杭州翠微亭",
       "weizhi" :              "/d/hangzhou/cuiweiting",]),
     (["chinese":                "杭州聚景园",
       "weizhi" :              "/d/hangzhou/jujingyuan",]),
     (["chinese":                "苗疆易溪部",
       "weizhi" :              "/d/dali/yixibu",]),  
      (["chinese":                "扬州中央广场",
       "weizhi" :              "/d/city/guangchang",]),  
      (["chinese":                "杭州沿湖大道",
       "weizhi" :              "/d/hangzhou/dadao1",]), 
      (["chinese":                "杭州断桥",
       "weizhi" :              "/d/hangzhou/duanqiao",]), 
      (["chinese":                "杭州灵隐寺",
       "weizhi" :              "/d/hangzhou/lingyinsi",]), 
      (["chinese":                "星宿海伊犁",
       "weizhi" :              "/d/xingxiu/beijiang",]), 
      (["chinese":                "武当三天门",
       "weizhi" :              "/d/wudang/santiangate",]), 
      (["chinese":                "峨嵋十二盘",
       "weizhi" :              "/d/emei/shierpan3",]), 
      (["chinese":                "峨嵋千佛庵",
       "weizhi" :              "/d/emei/qianfoan",]), 
      (["chinese":                "峨嵋九十九道拐",
       "weizhi" :              "/d/emei/jsjdg1",]), 
      (["chinese":                "明教厚土旗门",
       "weizhi" :              "/d/mingjiao/htqmen",]), 
      (["chinese":                "明教烈火旗后门",
       "weizhi" :              "/d/mingjiao/lhqhoumen",]), 
      (["chinese":                "福州东门",
       "weizhi" :              "/d/fuzhou/dongmen",]), 
      (["chinese":                "福州北大街",
       "weizhi" :              "/d/fuzhou/beidajie",]), 
      (["chinese":                "星宿海沙漠",
       "weizhi" :              "/d/xingxiu/shamo2",]),
      (["chinese":                "少林寺石阶",
       "weizhi" :              "/d/shaolin/shijie4",]),
      (["chinese":                "襄阳石阶",
       "weizhi" :              "/d/xiangyang/walle1",]),
      (["chinese":                "华山猢狲愁",
       "weizhi" :              "/d/huashan/husun",]),
      (["chinese":                "华山玉女峰",
       "weizhi" :              "/d/huashan/yunu",]),
      (["chinese":                "慕容小径",
       "weizhi" :              "/d/mr/xiaojing1-2",]),
      (["chinese":                "慕容柳树林",
       "weizhi" :              "/d/mr/liulin",]),
      (["chinese":                "大理大和街",
       "weizhi" :              "/d/dali/dahejiewest",]),
      (["chinese":                "苏州城北门",
       "weizhi" :              "/d/suzhou/beimen",]),
      (["chinese":                "苏州城玄妙观",
       "weizhi" :              "/d/suzhou/xuanmiao",]),
      (["chinese":                "少林寺山门殿",
       "weizhi" :              "/d/shaolin/smdian",]),
      (["chinese":                "少林寺走廊",
       "weizhi" :              "/d/shaolin/zoulang7",]),
      (["chinese":                "武当山路",
       "weizhi" :              "/d/wudang/shanlu3",]),
      (["chinese":                "少林寺般若堂九部",
       "weizhi" :              "/d/shaolin/banruo9",]),
      (["chinese":                "雪山山脚",
       "weizhi" :              "/d/xueshan/shanjiao",]),
      (["chinese":                "峨嵋九老洞",
       "weizhi" :              "/d/emei/jiulaodong",]),
       (["chinese":                "峨嵋古德林",
       "weizhi" :              "/d/emei/gudelin1",]),
       (["chinese":                "长安函古关",
       "weizhi" :              "/d/city4/hanguguan",]),
       (["chinese":                "长安终南山口",
       "weizhi" :              "/d/city4/zhongnan",]),
       (["chinese":                "福州闽江",
       "weizhi" :              "/d/fuzhou/fzroad8",]),
       (["chinese":                "汉水南岸",
       "weizhi" :              "/d/shaolin/hanshui1",]),
       (["chinese":                "华山中条山密林",
       "weizhi" :              "/d/huashan/jzroad5",]),
       (["chinese":                "天山脚下",
       "weizhi" :              "/d/xingxiu/shanjiao",]),
       (["chinese":                "华山脚下",
       "weizhi" :              "/d/huashan/path1",]),
       (["chinese":                "平定州",
       "weizhi" :              "/d/heimuya/pingdingzhou",]),
       (["chinese":                "黑木崖乱石坡",
       "weizhi" :              "/d/heimuya/road1",]),      
       (["chinese":                "华山村南村口",
       "weizhi":                "/d/village/sexit",]),
       (["chinese":                "闽赣古道",
       "weizhi":                "/d/fuzhou/fzroad7",]),
       (["chinese":                "泰山玉皇顶",
       "weizhi":               "/d/taishan/yuhuang",]),
       (["chinese":                "星宿六盘山",
       "weizhi":                "/d/xingxiu/xxroad3",]),
       (["chinese":                "星宿天山山路",
       "weizhi":                "/d/xingxiu/tianroad1",]),
       (["chinese":                "星宿嘉峪关",
       "weizhi":                "/d/xingxiu/jiayuguan",]),
       (["chinese":                "北京西单北大街",
       "weizhi":                "/d/beijing/xidan1",]),
       (["chinese":                "扬州通泗桥",
       "weizhi":                "/d/city/tongsiqiao",]),
       (["chinese":                "北京王府井大街",
       "weizhi":                "/d/beijing/wangfu2",]),
       (["chinese":                "全真教碑",
       "weizhi":                "/d/quanzhen/jiaobei",]),
       (["chinese":                "全真老妪岩",
       "weizhi":                "/d/gumu/juyan",]),
       (["chinese":                "关外老龙头",
       "weizhi":                "/d/guanwai/laolongtou",]),
       (["chinese":                "嘉兴城",
       "weizhi":                "/d/jiaxing/jiaxing",]),
       (["chinese":                "扬州西门",
       "weizhi":                "/d/city/ximen",]),
       (["chinese":                "福州仙霞岭",
       "weizhi":                "/d/fuzhou/fzroad1",]),
       (["chinese":                "泰山一天门",
       "weizhi":                "/d/taishan/yitian",]),
       (["chinese":                "关外小土屋",
       "weizhi":                "/d/guanwai/tuwu",]),
       (["chinese":                "大理下关城",
       "weizhi":                "/d/dali/xiaguan",]),
       (["chinese":                "大理李子箐石林",
        "weizhi":                "/d/dali/shilin1",]),
        (["chinese":                "大理大叠水瀑布",
        "weizhi":                "/d/dali/dadieshui",]),
        (["chinese":                "大理罗伽甸",
        "weizhi":                "/d/dali/luojiadian",]),
        (["chinese":                "大理阳宗镇",
        "weizhi":                "/d/dali/yangzong",]),
        (["chinese":                "少林太室阙",
        "weizhi":                "/d/songshan/taishique",]),
        (["chinese":                "少林石阶",
        "weizhi":                "/d/shaolin/shijie7",]),
        (["chinese":                "嵩山铁梁峡",
        "weizhi":                "/d/songshan/tieliang",]),
        (["chinese":                "嵩山峻极禅院山门",
        "weizhi":                "/d/songshan/junjigate",]),
        (["chinese":                "古墓神禾原",
        "weizhi":                "/d/gumu/shenheyuan",]),
        (["chinese":                "终南山大校场",
        "weizhi":                "/d/gumu/daxiaochang",]),
        (["chinese":                "华山金锁关",
        "weizhi":                "/d/huashan/jinsuo",]),
        (["chinese":                "华山平心石",
        "weizhi":                "/d/huashan/pingxinshi",]),
        (["chinese":                "华山千尺幢",
        "weizhi":                "/d/huashan/qianchi",]),
        (["chinese":                "华山山洪瀑布",
        "weizhi":                "/d/huashan/shanhongpb",]),
        (["chinese":                "峨嵋清音阁",
        "weizhi":                "/d/emei/qingyinge",]),
        (["chinese":                "峨嵋九老洞口",
        "weizhi":                "/d/emei/jldongkou",]),
        (["chinese":                "峨嵋千佛庵",
        "weizhi":                "/d/emei/qianfoan",]),
        (["chinese":                "终南山空地",
        "weizhi":                "/d/gumu/kongdi",]),
        (["chinese":                "终南山主峰",
        "weizhi":                "/d/gumu/zhufeng",]),
        (["chinese":                "明教悬天崖",
        "weizhi":                "/d/mingjiao/shanlu3",]),
         (["chinese":                "明教烈火旗大门",
        "weizhi":                "/d/mingjiao/lhqmen",]),
        (["chinese":                "雪山寺山门",
        "weizhi":                "/d/xueshan/shanmen",]),
        (["chinese":                "明教洪水旗大门",
        "weizhi":                "/d/mingjiao/hsqmen",]),
        (["chinese":                "武当青石大道",
        "weizhi":                "/d/wudang/wdroad1",]),
        (["chinese":                "长安关洛道",
        "weizhi":                "/d/city4/road1",]),
        (["chinese":                "泰山大驿道",
        "weizhi":                "/d/taishan/yidao",]),
        (["chinese":                "全真官道",
        "weizhi":                "/d/quanzhen/guandao2",]),
        (["chinese":                "武功镇东街",
        "weizhi":                "/d/quanzhen/dongjie",]),
        (["chinese":                "武功镇富家大门",
        "weizhi":                "/d/quanzhen/fu-damen",]),
        (["chinese":                "全真山路",
        "weizhi":                "/d/quanzhen/shanlu1",]),
        (["chinese":                "全真小村庄",
        "weizhi":                "/d/quanzhen/xiaocun",]),
        (["chinese":                "星宿海",
        "weizhi":                "/d/xingxiu/xxh2",]),
        (["chinese":                "星宿天山脚下",
        "weizhi":                "/d/xingxiu/shanjiao",]),
        (["chinese":                "星宿丝绸之路",
        "weizhi":                "/d/xingxiu/silk2",]),
        (["chinese":                "长安城西门",
        "weizhi":                "/d/city4/westgate",]),
        (["chinese":                "长安城东门",
        "weizhi":                "/d/city4/eastgate",]),
        (["chinese":                "华山上天梯",
        "weizhi":                "/d/huashan/shangtianti",]),
        (["chinese":                "逍遥树林",
        "weizhi":                "/d/xiaoyao/shulin3",]),
        (["chinese":                "扬州南门",
         "weizhi":                "/d/city/nanmen",
        ]),
       (["chinese":     "崆峒轩辕宫",
       "weizhi" :   "/d/xibei/kongdong/xuanyuan_gong",]),       
       (["chinese":     "大理天龙寺大门",
       "weizhi" :   "/d/tianlongsi/damen",]),       
       (["chinese":     "蜀中唐门竹林",
       "weizhi" :   "/d/tangmen/zhulin",]),       
       (["chinese":     "太原城西大街",
       "weizhi" :   "/d/taiyuan/xidajie1",]),       
       (["chinese":     "合肥城西大街",
       "weizhi" :   "/d/hefei/xidajie3",]),       
       (["chinese":     "九江城东大街",
       "weizhi" :   "/d/jiujiang/dongdajie2",]),       
       (["chinese":     "碎叶城北大街",
       "weizhi" :   "/d/suiye/beidajie1",]),       
       (["chinese":     "定襄城北大街",
       "weizhi" :   "/d/dingxiang/beidajie1",]),       
       (["chinese":     "新疆乌拉泊北门",
       "weizhi" :   "/d/xinjiang/nanmen",]),       
       (["chinese":     "徐州城西大街",
       "weizhi" :   "/d/xuzhou/xidajie",]),       
       (["chinese":     "贵阳城十字街头",
       "weizhi" :   "/d/guizhou/center",]),       
       (["chinese":     "南昌城广场",
       "weizhi" :   "/d/nanchang/center",]),       
       (["chinese":     "长沙城广场",
       "weizhi" :   "/d/changsha/guangchang",]),       
       (["chinese":     "宁远城官府驿站",
       "weizhi" :   "/d/ny/postoffice",]),       
       (["chinese":     "关外盛京十字路口",
       "weizhi" :   "/d/fengtian/cross",]),       
       (["chinese":     "神古活心流大门",
       "weizhi" :   "/d/feitian/damen",]),       
       (["chinese":     "中州苗家大门",
       "weizhi" :   "/d/zhongzhou/miaojia_men",]),       
       (["chinese":     "青城建福宫",
       "weizhi" :   "/d/qingcheng/jianfugong",]),       
       (["chinese":     "嵩山太室阙",
       "weizhi" :   "/d/songshan/taishique",]),       
       (["chinese":     "泰山岱宗坊",
       "weizhi" :   "/d/taishan/daizong",]),       
       (["chinese":     "华山莎萝坪",
       "weizhi" :   "/d/huashan/shaluo",]),       
       (["chinese":     "衡山棂星门",
       "weizhi" :   "/d/henshan/lingxingmen",]),       
       (["chinese":     "恒山金龙峡",
       "weizhi" :   "/d/hengshan/jinlongxia",]),       
       (["chinese":     "全真派山脚",
       "weizhi" :   "/d/quanzhen/shanjiao",]),       
       (["chinese":     "长白山白河",
       "weizhi" :   "/d/guanwai/baihe",]),       
       (["chinese":     "光明顶山门",
       "weizhi" :   "/d/mingjiao/shanmen",]),       
       (["chinese":     "雪山寺山门",
       "weizhi" :   "/d/xueshan/shanmen",]),       
       (["chinese":     "凌霄城石崖",
       "weizhi" :   "/d/lingxiao/shiya",]),       
       (["chinese":     "星宿派天山山路",
       "weizhi" :   "/d/xingxiu/tianroad2",]),       
       (["chinese":     "慕容世家码头",
       "weizhi" :   "/d/mr/matou",]),       
       (["chinese":     "日月神教乱石坡",
       "weizhi" :   "/d/heimuya/road1",]),       
       (["chinese":     "落雁山落雁山庄",
       "weizhi" :   "/d/yandang/luoyan2",]),       
       (["chinese":     "铁掌峰山脚下",
       "weizhi" :   "/d/tiezhang/shanjiao",]),       
       (["chinese":     "昆仑派山门",
       "weizhi" :   "/d/kunlun/shanmen",]),       
       (["chinese":     "峨眉报国寺",
       "weizhi" :   "/d/emei/bgs",]),       
       (["chinese":     "武当解剑岩",
       "weizhi" :   "/d/wudang/jiejianyan",]),       
       (["chinese":     "南少林迎客亭",
       "weizhi" :   "/d/nanshaolin/ting",]),       
       (["chinese":     "少林寺山门",
       "weizhi" :   "/d/shaolin/shanmen",]),       
       (["chinese":     "缥缈峰山脚",
       "weizhi" :   "/d/lingjiu/shanjiao",]),       
       (["chinese":     "白驼山庄大厅",
       "weizhi" :   "/d/baituo/dating",]),       
       (["chinese":     "桃花岛大厅",
       "weizhi" :   "/d/taohua/dating",]),       
       (["chinese":     "神龙教大厅",
       "weizhi" :   "/d/shenlong/dating",]),       
       (["chinese":     "红花会大门",
       "weizhi" :   "/d/huizhu/damen",]),       
       (["chinese":     "大理王府大门",
       "weizhi" :   "/d/dali/wangfugate",]),       
       (["chinese":     "丐帮破庙",
       "weizhi" :   "/d/city/pomiao",]),       
       (["chinese":     "昆明近日古楼",
       "weizhi" :   "/d/kunming/jinrilou",]),     
       (["chinese":     "北京天安门",
       "weizhi" :   "/d/beijing/tian_anm",]),     
       (["chinese":     "苏州沧浪亭",
       "weizhi" :   "/d/suzhou/canlangting",]),     
       (["chinese":     "襄阳广场",
       "weizhi" :   "/d/xiangyang/guangchang",]),     
       (["chinese":     "长安城大街",
       "weizhi" :   "/d/changan/ca",]),     
       (["chinese":     "成都天府广场",
       "weizhi" :   "/d/chengdu/guangchang",]),     
       (["chinese":     "兰州广场",
       "weizhi" :   "/d/lanzhou/guangchang",]),     
       (["chinese":     "荆州中心",
       "weizhi" :   "/d/jingzhou/guangchang",]),     
       (["chinese":     "灵州城中心",
       "weizhi" :   "/d/lingzhou/center",]),     
       (["chinese":     "沧州北门",
       "weizhi" :   "/d/cangzhou/beimen",]),     
       (["chinese":     "宜兴",
       "weizhi" :   "/d/yixing/yixing",]),     
       (["chinese":     "塘沽北城门",
       "weizhi" :   "/d/tanggu/beimen",]),     
       (["chinese":     "岳阳广场",
       "weizhi" :   "/d/yueyang/guangchang",]),     
       (["chinese":     "江陵北城门",
       "weizhi" :   "/d/jiangling/beimen",]),     
       (["chinese":     "西藏城门",
       "weizhi" :   "/d/xizang/citygate",]),
       (["chinese":     "安南海防码头",
       "weizhi" :   "/d/annan/matou",]),
       (["chinese":     "高丽港口",
       "weizhi" :   "/d/gaoli/gangkou",]),                  
           });



mapping *quest = ({
    (["short":                "大理北门",
       "place" :              "/d/dali/northgate",]),  
      (["short":                "扬州密林",
       "place" :              "/d/city/jiaowai5",]),  
     (["short":                "峨嵋草棚",
       "place" :              "/d/emei/caopeng",]),
     (["short":                "扬州西门",
       "place" :              "/d/city/ximen",]),
     (["short":                "雪山土路",
       "place" :              "/d/xueshan/tulu2",]),
     (["short":                "苏州留园",
       "place" :              "/d/suzhou/liuyuan",]),
     (["short":                "苏州寒山寺",
       "place" :              "/d/suzhou/hanshansi",]),
     (["short":                "杭州飞来峰",
       "place" :              "/d/hangzhou/feilaifeng",]),
     (["short":                "杭州净慈寺",
       "place" :              "/d/hangzhou/jingcisi",]),
     (["short":                "杭州翠微亭",
       "place" :              "/d/hangzhou/cuiweiting",]),
     (["short":                "杭州聚景园",
       "place" :              "/d/hangzhou/jujingyuan",]),
     (["short":                "苗疆易溪部",
       "place" :              "/d/dali/yixibu",]),  
      (["short":                "扬州中央广场",
       "place" :              "/d/city/guangchang",]),  
      (["short":                "杭州沿湖大道",
       "place" :              "/d/hangzhou/dadao1",]), 
      (["short":                "杭州断桥",
       "place" :              "/d/hangzhou/duanqiao",]), 
      (["short":                "杭州灵隐寺",
       "place" :              "/d/hangzhou/lingyinsi",]), 
      (["short":                "星宿海伊犁",
       "place" :              "/d/xingxiu/beijiang",]), 
      (["short":                "武当三天门",
       "place" :              "/d/wudang/santiangate",]), 
      (["short":                "峨嵋十二盘",
       "place" :              "/d/emei/shierpan3",]), 
      (["short":                "峨嵋千佛庵",
       "place" :              "/d/emei/qianfoan",]), 
      (["short":                "峨嵋九十九道拐",
       "place" :              "/d/emei/jsjdg1",]), 
      (["short":                "明教厚土旗门",
       "place" :              "/d/mingjiao/htqmen",]), 
      (["short":                "明教烈火旗后门",
       "place" :              "/d/mingjiao/lhqhoumen",]), 
      (["short":                "福州东门",
       "place" :              "/d/fuzhou/dongmen",]), 
      (["short":                "福州北大街",
       "place" :              "/d/fuzhou/beidajie",]), 
      (["short":                "星宿海沙漠",
       "place" :              "/d/xingxiu/shamo2",]),
      (["short":                "少林寺石阶",
       "place" :              "/d/shaolin/shijie4",]),
      (["short":                "襄阳石阶",
       "place" :              "/d/xiangyang/walle1",]),
      (["short":                "华山猢狲愁",
       "place" :              "/d/huashan/husun",]),
      (["short":                "华山玉女峰",
       "place" :              "/d/huashan/yunu",]),
      (["short":                "慕容小径",
       "place" :              "/d/mr/xiaojing1-2",]),
      (["short":                "慕容柳树林",
       "place" :              "/d/mr/liulin",]),
      (["short":                "大理大和街",
       "place" :              "/d/dali/dahejiewest",]),
      (["short":                "苏州城北门",
       "place" :              "/d/suzhou/beimen",]),
      (["short":                "苏州城玄妙观",
       "place" :              "/d/suzhou/xuanmiao",]),
      (["short":                "少林寺山门殿",
       "place" :              "/d/shaolin/smdian",]),
      (["short":                "少林寺走廊",
       "place" :              "/d/shaolin/zoulang7",]),
      (["short":                "武当山路",
       "place" :              "/d/wudang/shanlu3",]),
      (["short":                "少林寺般若堂九部",
       "place" :              "/d/shaolin/banruo9",]),
      (["short":                "雪山山脚",
       "place" :              "/d/xueshan/shanjiao",]),
      (["short":                "峨嵋九老洞",
       "place" :              "/d/emei/jiulaodong",]),
       (["short":                "峨嵋古德林",
       "place" :              "/d/emei/gudelin1",]),
       (["short":                "长安函古关",
       "place" :              "/d/city4/hanguguan",]),
       (["short":                "终南山口",
       "place" :              "/d/city4/zhongnan",]),
       (["short":                "福州闽江",
       "place" :              "/d/fuzhou/fzroad8",]),
       (["short":                "汉水南岸",
       "place" :              "/d/shaolin/hanshui1",]),
       (["short":                "华山中条山密林",
       "place" :              "/d/huashan/jzroad5",]),
       (["short":                "星宿天山脚下",
       "place" :              "/d/xingxiu/shanjiao",]),
       (["short":                "华山脚下",
       "place" :              "/d/huashan/path1",]),
       (["short":                "平定州",
       "place" :              "/d/heimuya/pingdingzhou",]),
       (["short":                "黑木崖乱石坡",
       "place" :              "/d/heimuya/road1",]),      
       ([      "short":                "华山村南村口",
                "place":                "/d/village/sexit",
        ]),([      "short":                "福州闽赣古道",
                "place":                "/d/fuzhou/fzroad7",
        ]),([     "short":                "泰山玉皇顶",
                 "place":               "/d/taishan/yuhuang",
         ]),([      "short":                "星宿六盘山",
                "place":                "/d/xingxiu/xxroad3",
        ]),([      "short":                "星宿天山山路",
                "place":                "/d/xingxiu/tianroad1",
        ]),([      "short":                "星宿嘉峪关",
                "place":                "/d/xingxiu/jiayuguan",
        ]),([      "short":                "北京西单北大街",
                "place":                "/d/beijing/xidan1",
        ]),([      "short":                "扬州兵营",
                "place":                "/d/city/bingyin",
        ]),([      "short":                "北京王府井大街",
                "place":                "/d/beijing/wangfu2",
        ]),([      "short":                "全真教碑",
                "place":                "/d/quanzhen/jiaobei",
        ]),([      "short":                "全真老妪岩",
                "place":                "/d/gumu/juyan",
        ]),([      "short":                "关外老龙头",
                "place":                "/d/guanwai/laolongtou",
        ]),([      "short":                "嘉兴城",
                "place":                "/d/jiaxing/jiaxing",
        ]),([      "short":                "扬州西门",
                "place":                "/d/city/ximen",
        ]),([      "short":                "福州仙霞岭",
                "place":                "/d/fuzhou/fzroad1",
        ]),([      "short":                "泰山一天门",
                "place":                "/d/taishan/yitian",
        ]),([      "short":                "小土屋",
                "place":                "/d/guanwai/tuwu",
        ]),([      "short":                "大理下关城",
                "place":                "/d/dali/xiaguan",
        ]),([      "short":                "大理李子箐石林",
                 "place":                "/d/dali/shilin1",
        ]),([      "short":                "大理大叠水瀑布",
                 "place":                "/d/dali/dadieshui",
        ]),([      "short":                "大理罗伽甸",
                 "place":                "/d/dali/luojiadian",
        ]),([      "short":                "大理阳宗镇",

                 "place":                "/d/dali/yangzong",
        ]),([      "short":                "少林太室阙",
                 "place":                "/d/songshan/taishique",
        ]),([      "short":                "少林石阶",
                 "place":                "/d/shaolin/shijie7",
        ]),([      "short":                "嵩山铁梁峡",
                 "place":                "/d/songshan/tieliang",
        ]),([      "short":                "嵩山峻极禅院山门",
                 "place":                "/d/songshan/junjigate",
        ]),([      "short":                "古墓神禾原",
                 "place":                "/d/gumu/shenheyuan",
        ]),([      "short":                "终南山大校场",
                 "place":                "/d/gumu/daxiaochang",
        ]),([      "short":                "华山金锁关",
                 "place":                "/d/huashan/jinsuo",
        ]),([      "short":                "华山平心石",
                 "place":                "/d/huashan/pingxinshi",
        ]),([      "short":                "华山千尺幢",
                 "place":                "/d/huashan/qianchi",
        ]),([      "short":                "华山山洪瀑布",
                 "place":                "/d/huashan/shanhongpb",
        ]),([      "short":                "峨嵋清音阁",
                 "place":                "/d/emei/qingyinge",
        ]),([      "short":                "峨嵋九老洞口",
                 "place":                "/d/emei/jldongkou",
        ]),([      "short":                "峨嵋千佛庵",
                 "place":                "/d/emei/qianfoan",
        ]),([      "short":                "终南山空地",
                 "place":                "/d/gumu/kongdi",
        ]),([      "short":                "终南山主峰",
                 "place":                "/d/gumu/zhufeng",
        ]),([      "short":                "明教悬天崖",
                 "place":                "/d/mingjiao/shanlu3",
        ]), ([      "short":                "明教烈火旗大门",
                 "place":                "/d/mingjiao/lhqmen",
        ]),([      "short":                "雪山寺山门",
                 "place":                "/d/xueshan/shanmen",
        ]),([      "short":                "明教洪水旗大门",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "武当青石大道",
                 "place":                "/d/wudang/wdroad1",
        ]),([      "short":                "长安关洛道",
                 "place":                "/d/city4/road1",
        ]),([      "short":                "泰山大驿道",
                 "place":                "/d/taishan/yidao",
        ]),([      "short":                "全真官道",
                 "place":                "/d/quanzhen/guandao2",
        ]),([      "short":                "武功镇东街",
                 "place":                "/d/quanzhen/dongjie",
        ]),([      "short":                "武功镇富家大门",
                 "place":                "/d/quanzhen/fu-damen",
        ]),([      "short":                "全真山路",
                 "place":                "/d/quanzhen/shanlu1",
        ]),([      "short":                "全真小村庄",
                 "place":                "/d/quanzhen/xiaocun",
        ]),([      "short":                "星宿海",
                 "place":                "/d/xingxiu/xxh2",
        ]),([      "short":                "星宿天山脚下",
                 "place":                "/d/xingxiu/shanjiao",
        ]),([      "short":                "星宿丝绸之路",
                 "place":                "/d/xingxiu/silk2",

        ]),([      "short":                "长安城西门",
                 "place":                "/d/city4/westgate",
        ]),([      "short":                "长安城东门",
                 "place":                "/d/city4/eastgate",
        ]),([      "short":                "华山上天梯",
                 "place":                "/d/huashan/shangtianti",
        ]),([      "short":                "逍遥树林",
                 "place":                "/d/xiaoyao/shulin3",
        ]),([      "short":                "扬州南门",
                 "place":                "/d/city/nanmen",
        ]),      
       (["short":     "崆峒轩辕宫",
       "place" :   "/d/xibei/kongdong/xuanyuan_gong",]),       
       (["short":     "大理天龙寺大门",
       "place" :   "/d/tianlongsi/damen",]),       
       (["short":     "蜀中唐门竹林",
       "place" :   "/d/tangmen/zhulin",]),       
       (["short":     "太原城西大街",
       "place" :   "/d/taiyuan/xidajie1",]),       
       (["short":     "合肥城西大街",
       "place" :   "/d/hefei/xidajie3",]),       
       (["short":     "九江城东大街",
       "place" :   "/d/jiujiang/dongdajie2",]),       
       (["short":     "碎叶城北大街",
       "place" :   "/d/suiye/beidajie1",]),       
       (["short":     "定襄城北大街",
       "place" :   "/d/dingxiang/beidajie1",]),       
       (["short":     "新疆乌拉泊北门",
       "place" :   "/d/xinjiang/nanmen",]),       
       (["short":     "徐州城西大街",
       "place" :   "/d/xuzhou/xidajie",]),       
       (["short":     "贵阳城十字街头",
       "place" :   "/d/guizhou/center",]),       
       (["short":     "南昌城广场",
       "place" :   "/d/nanchang/center",]),       
       (["short":     "长沙城广场",
       "place" :   "/d/changsha/guangchang",]),       
       (["short":     "宁远城官府驿站",
       "place" :   "/d/ny/postoffice",]),       
       (["short":     "关外盛京十字路口",
       "place" :   "/d/fengtian/cross",]),       
       (["short":     "神古活心流大门",
       "place" :   "/d/feitian/damen",]),       
       (["short":     "中州苗家大门",
       "place" :   "/d/zhongzhou/miaojia_men",]),       
       (["short":     "青城建福宫",
       "place" :   "/d/qingcheng/jianfugong",]),       
       (["short":     "嵩山太室阙",
       "place" :   "/d/songshan/taishique",]),       
       (["short":     "泰山岱宗坊",
       "place" :   "/d/taishan/daizong",]),       
       (["short":     "华山莎萝坪",
       "place" :   "/d/huashan/shaluo",]),       
       (["short":     "衡山棂星门",
       "place" :   "/d/henshan/lingxingmen",]),       
       (["short":     "恒山金龙峡",
       "place" :   "/d/hengshan/jinlongxia",]),       
       (["short":     "全真派山脚",
       "place" :   "/d/quanzhen/shanjiao",]),       
       (["short":     "长白山白河",
       "place" :   "/d/guanwai/baihe",]),       
       (["short":     "光明顶山门",
       "place" :   "/d/mingjiao/shanmen",]),       
       (["short":     "雪山寺山门",
       "place" :   "/d/xueshan/shanmen",]),       
       (["short":     "凌霄城石崖",
       "place" :   "/d/lingxiao/shiya",]),       
       (["short":     "星宿派天山山路",
       "place" :   "/d/xingxiu/tianroad2",]),       
       (["short":     "慕容世家码头",
       "place" :   "/d/mr/matou",]),       
       (["short":     "日月神教乱石坡",
       "place" :   "/d/heimuya/road1",]),       
       (["short":     "落雁山落雁山庄",
       "place" :   "/d/yandang/luoyan2",]),       
       (["short":     "铁掌峰山脚下",
       "place" :   "/d/tiezhang/shanjiao",]),       
       (["short":     "昆仑派山门",
       "place" :   "/d/kunlun/shanmen",]),       
       (["short":     "峨眉报国寺",
       "place" :   "/d/emei/bgs",]),       
       (["short":     "武当解剑岩",
       "place" :   "/d/wudang/jiejianyan",]),       
       (["short":     "南少林迎客亭",
       "place" :   "/d/nanshaolin/ting",]),       
       (["short":     "少林寺山门",
       "place" :   "/d/shaolin/shanmen",]),       
       (["short":     "缥缈峰山脚",
       "place" :   "/d/lingjiu/shanjiao",]),       
       (["short":     "白驼山庄大厅",
       "place" :   "/d/baituo/dating",]),       
       (["short":     "桃花岛大厅",
       "place" :   "/d/taohua/dating",]),       
       (["short":     "神龙教大厅",
       "place" :   "/d/shenlong/dating",]),       
       (["short":     "红花会大门",
       "place" :   "/d/huizhu/damen",]),       
       (["short":     "大理王府大门",
       "place" :   "/d/dali/wangfugate",]),       
       (["short":     "丐帮破庙",
       "place" :   "/d/city/pomiao",]),       
       (["short":     "昆明近日古楼",
       "place" :   "/d/kunming/jinrilou",]),     
       (["short":     "北京天安门",
       "place" :   "/d/beijing/tian_anm",]),     
       (["short":     "苏州沧浪亭",
       "place" :   "/d/suzhou/canlangting",]),     
       (["short":     "襄阳广场",
       "place" :   "/d/xiangyang/guangchang",]),     
       (["short":     "长安城大街",
       "place" :   "/d/changan/ca",]),     
       (["short":     "成都天府广场",
       "place" :   "/d/chengdu/guangchang",]),     
       (["short":     "兰州广场",
       "place" :   "/d/lanzhou/guangchang",]),     
       (["short":     "荆州中心",
       "place" :   "/d/jingzhou/guangchang",]),     
       (["short":     "灵州城中心",
       "place" :   "/d/lingzhou/center",]),     
       (["short":     "沧州北门",
       "place" :   "/d/cangzhou/beimen",]),     
       (["short":     "宜兴",
       "place" :   "/d/yixing/yixing",]),     
       (["short":     "塘沽北城门",
       "place" :   "/d/tanggu/beimen",]),     
       (["short":     "岳阳广场",
       "place" :   "/d/yueyang/guangchang",]),     
       (["short":     "江陵北城门",
       "place" :   "/d/jiangling/beimen",]),     
       (["short":     "西藏城门",
       "place" :   "/d/xizang/citygate",]),
       (["short":     "安南海防码头",
       "place" :   "/d/annan/matou",]),
       (["short":     "高丽港口",
       "place" :   "/d/gaoli/gangkou",]),

   

      });

mapping query_quest()
{
  return quest[random(sizeof(quest))];
}
