mapping *dest = ({
 ([ "name":"luanshigang",
           "context": ({
"/d/houjizhen/shigang",
"/d/houjizhen/lzxiaolu",
"/d/houjizhen/songlin1",
"/d/houjizhen/songlin2",
"/d/houjizhen/guanmu",
"/d/houjizhen/shanlu5",
"/d/houjizhen/shanlu4",
"/d/houjizhen/shanlu2",
"/d/houjizhen/shanlu1",
"/d/houjizhen/shanpo",
"/d/houjizhen/shigang",
"/d/houjizhen/tomb",
})]),

 ([ "name":"shangang",
           "context": ({
"/d/houjizhen/shangang",
"/d/houjizhen/tomb",
"/d/houjizhen/shigang",
"/d/houjizhen/lzxiaolu",
"/d/houjizhen/songlin1",
"/d/houjizhen/songlin2",
"/d/houjizhen/guanmu",
"/d/houjizhen/shanlu5",
"/d/houjizhen/shanlu4",
"/d/houjizhen/shanlu2",
"/d/houjizhen/shanlu1",
"/d/houjizhen/shanpo",
})]),
([ "name":"xiaoshulin",
           "context": ({
"/d/houjizhen/shanlu3",
"/d/houjizhen/shanlu2",
"/d/houjizhen/shanlu4",
"/d/houjizhen/shanlu5",
"/d/houjizhen/guanmu",
"/d/houjizhen/songlin2",
"/d/houjizhen/songlin1",
"/d/houjizhen/lzxiaolu",
"/d/houjizhen/shigang",
"/d/houjizhen/shanpo",
"/d/houjizhen/shanlu1",
"/d/houjizhen/songlin2",
})]),
([ "name":"xiaoxi",
           "context": ({
"/d/houjizhen/xiaoxi",
"/d/houjizhen/shanlu4",
"/d/houjizhen/shanlu5",
"/d/houjizhen/guanmu",
"/d/houjizhen/songlin2",
"/d/houjizhen/songlin1",
"/d/houjizhen/lzxiaolu",
"/d/houjizhen/shigang",
"/d/houjizhen/shanpo",
"/d/houjizhen/shanlu1",
"/d/houjizhen/shanlu2",
"/d/houjizhen/shanlu3",
})]),
([ "name":"songshulin",
           "context": ({
"/d/houjizhen/songlin2",
"/d/houjizhen/songlin1",
"/d/houjizhen/lzxiaolu",
"/d/houjizhen/shigang",
"/d/houjizhen/shanpo",
"/d/houjizhen/shanlu1",
"/d/houjizhen/shanlu2",
"/d/houjizhen/shanlu4",
"/d/houjizhen/xiaoxi",
"/d/houjizhen/zhulin1",
"/d/houjizhen/zhulin2",
"/d/houjizhen/zhulin3",
})]),
([ "name":"shanlu",
           "context": ({
"/d/houjizhen/shanlu1",
"/d/houjizhen/shanlu2",
"/d/houjizhen/shanlu4",
"/d/houjizhen/shanlu5",
"/d/houjizhen/guanmu",
"/d/houjizhen/songlin2",
"/d/houjizhen/songlin1",
"/d/houjizhen/lzxiaolu",
"/d/houjizhen/shigang",
"/d/houjizhen/shanpo",
"/d/houjizhen/shanlu1",
"/d/houjizhen/shanlu2",
})]),

([ "name":"shanya",
           "context": ({
"/d/houjizhen/shanya",
"/d/houjizhen/qiaobi",
"/d/houjizhen/shanlu5",
"/d/houjizhen/guanmu",
"/d/houjizhen/songlin2",
"/d/houjizhen/songlin1",
"/d/houjizhen/lzxiaolu",
"/d/houjizhen/shigang",
"/d/houjizhen/shanpo",
"/d/houjizhen/shanlu1",
"/d/houjizhen/shanlu2",
"/d/houjizhen/shanlu3",
})]),
});

